-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2019-12-06 18:14:04 CET
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE Cell (
    cell_id            INTEGER NOT NULL,
    capacity           INTEGER NOT NULL CHECK (capacity >= 1),
    Prison_prison_id   INTEGER NOT NULL
)



ALTER TABLE Cell ADD CONSTRAINT Cell_PK PRIMARY KEY CLUSTERED (cell_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

CREATE TABLE Employee (
    employee_id        INTEGER NOT NULL,
    firstName          VARCHAR(50) NOT NULL,
    lastName           VARCHAR(50) NOT NULL,
    gender             CHAR(1) NOT NULL CHECK (gender IN ('M','F')),
    birthDate          DATE NOT NULL,
    warden             BIT NOT NULL,
    Prison_prison_id   INTEGER NOT NULL
)



ALTER TABLE Employee ADD CONSTRAINT Employee_PK PRIMARY KEY CLUSTERED (employee_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

CREATE TABLE Prison (
    prison_id                  INTEGER NOT NULL,
    address                    VARCHAR(50) NOT NULL,
    city                       VARCHAR(50) NOT NULL,
    PrisonType_prisonType_id   INTEGER NOT NULL
)



ALTER TABLE Prison ADD CONSTRAINT Prison_PK PRIMARY KEY CLUSTERED (prison_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

CREATE TABLE Prisoner (
    prisoner_id           INTEGER NOT NULL,
    firstName             VARCHAR(50) NOT NULL,
    lastName              VARCHAR(50) NOT NULL,
    gender                CHAR(1) NOT NULL CHECK (gender IN ('M','F')),
    birthDate             DATE NOT NULL,
    punishmentStartDate   DATE NOT NULL,
    punishmentEndDate     DATE NOT NULL,
    Cell_cell_id          INTEGER NOT NULL,
	CHECK (punishmentStartDate < punishmentEndDate)
)



ALTER TABLE Prisoner ADD CONSTRAINT Prisoner_PK PRIMARY KEY CLUSTERED (prisoner_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

CREATE TABLE PrisonerCellHistory (
    prisonerCellHistory_id   INTEGER NOT NULL,
    startDate                DATE NOT NULL,
    endDate                  DATE NOT NULL,
    Prisoner_prisoner_id     INTEGER NOT NULL,
    Cell_cell_id             INTEGER NOT NULL,
    Employee_employee_id     INTEGER NOT NULL
)



ALTER TABLE PrisonerCellHistory ADD CONSTRAINT PrisonerCellHistory_PK PRIMARY KEY CLUSTERED (prisonerCellHistory_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

CREATE TABLE PrisonType (
    prisonType_id   INTEGER NOT NULL,
    type            VARCHAR(50) NOT NULL
)



ALTER TABLE PrisonType ADD CONSTRAINT PrisonType_PK PRIMARY KEY CLUSTERED (prisonType_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

CREATE TABLE Visit (
    visit_id               INTEGER NOT NULL,
    firstName              VARCHAR(50) NOT NULL,
    lastName               VARCHAR(50) NOT NULL,
    gender                 CHAR(1) NOT NULL CHECK (gender IN ('M','F')),
    birthDate              DATE NOT NULL,
    visitDate              DATE NOT NULL,
    Prisoner_prisoner_id   INTEGER NOT NULL
)



ALTER TABLE Visit ADD CONSTRAINT Visit_PK PRIMARY KEY CLUSTERED (visit_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

ALTER TABLE Cell
    ADD CONSTRAINT Cell_Prison_FK FOREIGN KEY ( Prison_prison_id )
        REFERENCES Prison ( prison_id )
ON DELETE NO ACTION 
    ON UPDATE NO ACTION 

ALTER TABLE Employee
    ADD CONSTRAINT Employee_Prison_FK FOREIGN KEY ( Prison_prison_id )
        REFERENCES Prison ( prison_id )
ON DELETE NO ACTION 
    ON UPDATE NO ACTION 

ALTER TABLE Prison
    ADD CONSTRAINT Prison_PrisonType_FK FOREIGN KEY ( PrisonType_prisonType_id )
        REFERENCES PrisonType ( prisonType_id )
ON DELETE NO ACTION 
    ON UPDATE NO ACTION 

ALTER TABLE Prisoner
    ADD CONSTRAINT Prisoner_Cell_FK FOREIGN KEY ( Cell_cell_id )
        REFERENCES Cell ( cell_id )
ON DELETE NO ACTION 
    ON UPDATE NO ACTION 

ALTER TABLE PrisonerCellHistory
    ADD CONSTRAINT PrisonerCellHistory_Cell_FK FOREIGN KEY ( Cell_cell_id )
        REFERENCES Cell ( cell_id )
ON DELETE NO ACTION 
    ON UPDATE NO ACTION 

ALTER TABLE PrisonerCellHistory
    ADD CONSTRAINT PrisonerCellHistory_Employee_FK FOREIGN KEY ( Employee_employee_id )
        REFERENCES Employee ( employee_id )
ON DELETE NO ACTION 
    ON UPDATE NO ACTION 

ALTER TABLE PrisonerCellHistory
    ADD CONSTRAINT PrisonerCellHistory_Prisoner_FK FOREIGN KEY ( Prisoner_prisoner_id )
        REFERENCES Prisoner ( prisoner_id )
ON DELETE NO ACTION 
    ON UPDATE NO ACTION 

ALTER TABLE Visit
    ADD CONSTRAINT Visit_Prisoner_FK FOREIGN KEY ( Prisoner_prisoner_id )
        REFERENCES Prisoner ( prisoner_id )
ON DELETE NO ACTION 
    ON UPDATE NO ACTION 



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0