-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-04-03 22:00:00 CET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



CREATE TABLE Cell (
    cell_id           INTEGER NOT NULL,
    occupied          INTEGER NOT NULL,
	capacity          INTEGER NOT NULL
);

ALTER TABLE Cell ADD CONSTRAINT Cell_PK PRIMARY KEY ( cell_id );

CREATE TABLE Employee (
    employee_id       INTEGER NOT NULL,
    firstName         VARCHAR(50) NOT NULL,
    lastName          VARCHAR(50) NOT NULL,
    gender            CHAR(1),
    birthDate         DATE NOT NULL,
    warden            CHAR(1) NOT NULL,
	fired             CHAR(1) NOT NULL
);

ALTER TABLE Employee ADD CONSTRAINT Employee_PK PRIMARY KEY ( employee_id );

CREATE TABLE Prisoner (
    prisoner_id          INTEGER NOT NULL,
    firstName            VARCHAR(50) NOT NULL,
    lastName             VARCHAR(50) NOT NULL,
    gender               CHAR(1),
    birthDate            DATE NOT NULL,
    punishmentStartDate  DATE NOT NULL,
    punishmentEndDate    DATE NOT NULL,
	released             CHAR(1) NOT NULL,
    cell_id              INTEGER NOT NULL
);

ALTER TABLE Prisoner ADD CONSTRAINT Prisoner_PK PRIMARY KEY ( prisoner_id );

CREATE TABLE Visit (
    visit_id              INTEGER NOT NULL,
    visitDate             DATE NOT NULL,
    allowed               CHAR(1) NOT NULL,
    prisoner_id           INTEGER NOT NULL,
    visitor_id            INTEGER NOT NULL
);

CREATE UNIQUE INDEX Visit__IDXv1 ON
    Visit (
        visitDate
    ASC,
        prisoner_id
    ASC,
        visitor_id
    ASC );

ALTER TABLE Visit ADD CONSTRAINT Visit_PK PRIMARY KEY ( visit_id );

CREATE TABLE Visitor (
    visitor_id  INTEGER NOT NULL,
    firstName   VARCHAR(50) NOT NULL,
    lastName    VARCHAR(50) NOT NULL,
    gender      CHAR(1),
    birthDate   DATE NOT NULL,
    forbidden   CHAR(1) NOT NULL
);

ALTER TABLE Visitor ADD CONSTRAINT Visitor_PK PRIMARY KEY ( visitor_id );

ALTER TABLE Prisoner
    ADD CONSTRAINT Prisoner_Cell_FK FOREIGN KEY ( cell_id )
        REFERENCES Cell ( cell_id );

ALTER TABLE Visit
    ADD CONSTRAINT Visit_Prisoner_FK FOREIGN KEY ( prisoner_id )
        REFERENCES Prisoner ( prisoner_id );

ALTER TABLE Visit
    ADD CONSTRAINT Visit_Visitor_FK FOREIGN KEY ( visitor_id )
        REFERENCES Visitor ( visitor_id );



--  Integritni omezeni
ALTER TABLE Cell ADD CHECK(occupied >= 0 AND occupied <= capacity);
ALTER TABLE Cell ADD CHECK(capacity >= 1);
ALTER TABLE Employee ADD CHECK(warden IN('0','1'));
ALTER TABLE Employee ADD CHECK(fired IN('0','1'));
ALTER TABLE Prisoner ADD CHECK(punishmentStartDate < punishmentEndDate);
ALTER TABLE Prisoner ADD CHECK(released IN('0','1'));
ALTER TABLE Visit ADD CHECK(allowed IN(NULL,'0','1','2'));
ALTER TABLE Visitor ADD CHECK(forbidden IN('0','1'));



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             1
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0